* Applied Machine Learning

Welcome to my humble repository.

** Organization of the project

The purpose of this project is to deal with 4 recognition problems: Gender, Emotions, Face Shape and Eye Colour.

The classes containing data specific to each task are located in A1, A2, B1 and B2.

Besides that, utilities required to recognise faces, analyse them and plot results are located in tool/

If you wish to run this tool:
+ clone it
+ add the following file in the same directory as this readme: shape_predictor_68_face_landmarks.dat
  + Note: this file is available on moodle in the section about the last two labs
+ run main.py from the terminal

** Packages required to run your code

Here are the modules used to run this project and their version at the time of its completion.

#+begin_src
Python 3.10.9

numpy 1.24.1
matplotlib 3.6.3
pandas 1.5.2
sklearn 1.2.0
skimage 0.19.3
keras 2.11.0 (and tensorflow 2.11.0)
cv2 4.7.0
tqdm 4.64.1
dlib 19.24.0
#+end_src

* Results

Note that more than 20 variations of 4 models were used for predictions. The best of each type is given for each task.

** Tasl A1

| Model         | Accuracy |
|---------------+----------|
| Bagging (n=9) |   0.5975 |
| KNN (n=5)     |      0.7 |
| Random Forest |   0.8275 |
| SVM (poly)    |    0.914 |

** Task A2

| Model         | Accuracy |
|---------------+----------|
| Bagging (n=9) |    0.824 |
| KNN (n=7)     |    0.856 |
| Random Forest |    0.878 |
| SVM (poly)    |    0.894 |

** Task B1

| Model         | Accuracy |
|---------------+----------|
| Bagging (n=1) |    0.321 |
| KNN (n=8)     |    0.487 |
| Random Forest |    0.672 |
| SVM (poly)    |    0.736 |

** Task B2

| Model         | Accuracy |
|---------------+----------|
| Bagging (n=9) |    0.284 |
| KNN (n=9)     |    0.289 |
| Random Forest |    0.342 |
| SVM (poly)    |    0.376 |
